'\" t
.TH JG 1 "October 18th, 2017" "JSON Globber"
.
.\"---------------------------------------------------------------------
.\" DOCUMENT SETUP
.\"---------------------------------------------------------------------
.so ono.tmac
.
.ad l  \" Flush left
.nh    \" Screw hyphens
.
.ds .. \\.\&\\.\&\\.   \" Horizontal ellipsis
.
.# NAME
.B jg
\- print JSON values matching a glob pattern.
.
.
.\"---------------------------------------------------------------------
.	SH SYNOPSIS
.\"---------------------------------------------------------------------
.
'de F?
'	ie t \\f(\\$1\\$3
'	el   \\f(\\$2\\$3
..
.de *[
'	ie t \{
'		nr R CR
'		nr I CI
'		nr B CB
'		nr BI CBI
'	\}
'	el \{
'		nr R R
'		nr I I
'		nr B B
'		nr BI BI
'	\}
'	ds *$ \\f(\\nR[\\f(\\nB\\$1\\f(\\nR\~\\f\\nR\\$2
'	ie !'\\$3'' \
'		as *$ \~\\f(\\nI\\$3
'	as *$ \\f(\\nR\\]\\fP
.	if 1 \\*(*$
..
.B jg
.	*[ OPTIONS ]
.	*[ PATTERN ]
.	*[ FILE \*(..]
.br
.
.B jg
.	*[ OPTIONS ]
.	*[ \fB\-e\fP \ PATTERN \*(..
.	RI [ FILE \*(..]
.br
.
.B jg
.	RI [ OPTIONS ]
.	I    PATTERN
.	RI <\  INPUT
.
.
.\"---------------------------------------------------------------------
.	SH DESCRIPTION
.\"---------------------------------------------------------------------
.
.B jg
searches a stream of JSON-like data using a shell-like glob expression.
It behaves similarly to
.BR grep (1),
with property keys handled like filenames.
.
.PP
Input need not be strictly-formed JSON; any data representing a JavaScript object is acceptable.
.
.PP
Matched values are output as JSON.
This can cause data loss for certain elements, such as Symbol-keyed properties and RegExp values.
.
.
.\"---------------------------------------------------------------------
.	SH OPTIONS
.\"---------------------------------------------------------------------
.
.OP e expr | PATTERN
A glob expression to match keys whose values are to be printed.
It may be given multiple times; if omitted, the first argument is assumed to be the expression to use.
An exception is made if only one argument is given, and standard input is not from a terminal.
.
.OP k keys
Prefix each emitted value with its corresponding property name.
Keys are separated from values by a single tab character (\*(lq\et\*(rq or U+0009).
.
.OP K only\-keys
Like \fIkeys\fP, except \fBonly\fP the names of matching properties are output.
.
.OP i ignore\-case
Test each expression case-insensitively.
Locale is respected when considering letter equivalence.
.ig \" TODO
To force comparison by codepoint, set `LC_LOCALE=C` in your environment.
..
.OP m max\-depth - LEVELS
Limit traversal of nested properties to \fILEVELS\fP of recursion.
Values of \*(lq0\*(rq indicate no limit should be enforced;
the default value is \*(lq1\*(rq, matching only properties at root-level.
.
.OP v version
Output the program's version string and exit.
.
.
.\"---------------------------------------------------------------------
.	SH AUTHOR
.\"---------------------------------------------------------------------
.
Copyright \(co 2017 \c
'EM John\~Gardner "gardner\&john\&g\&@\&gmail.com"
